### ISSUE TITLE
Doesn't hide values in single quotes ''

### ISSUE THREAD

**Issue by sadranyi** [johnpapa/vscode-cloak#7]
When a secret is in single quotes it doesn't hide it 
example APP_NAME='CLOAK' will not be hidden, but APP_NAME="CLOAK" would be.
![2020-01-19_13-16-23](https://user-images.githubusercontent.com/564700/72681698-04fb5980-3abe-11ea-81e5-c4b301d2de2a.gif)

**Comment by johnpapa** [comment]
fixed in v0.2.0

thanks

**Comment by JimLynchCodes** [comment]
@johnpapa - this is **_NOT_** fixed... I just installed it, and it still does not hide  values in single quotes...

**Comment by johnpapa** [comment]
Can you provide some details so we can look into this please?
